def create_deskripsi():
    deskrip = [
        {"no":"1",  "description": 'Deskripsi produk.\n\nIni adalah gambar yang bagus dan sangan meykinkan'},
        {"no":"2",  "description": 'PROMO MURAH!!!!\n✔ LAPTOP HP ELITEBOOK 830 G5\n✔ INTEL CORE I7 8650U 8CPU / INTEL CORE 15 8650U 8CPU\n✔ RAM 16GB / 32GB\n✔ SSD 512GB/1TB\n✔ FULL HD 1920x1080\n✔ KEYBOARD BACKLIT\n✔ OS WINDOWS 11 PRO - OFFICE DLL\nBATERAI GOOD CONDITION\nALL PERFORMANCE 100% NORMAL\nUntuk unit yang kita jual semuanya ex display kondisi fisik like new 93-97% BUKAN BARANG BARU\n'
                                    'KELENGKAΡΑΝ: \nLaptop\nCharger\nDus Box\nKartu garansi toko\nFree tas dan mouse\nGaransi distributor 1 bulan (1 bulan untuk baterai, lcd dan keyboard. Garansi berlaku apa bila segel masih utuh, tidak terkena cairan dan belum pernah bongkar ditempat lain)\nTOKO REDSTAR ELECTRONIC'},
        {"no":"3",  "description": '1. Jenis: Laptop\nMerknya: SHINON\nUkuran: 371mm * 240mm * 21mm\nBerat: 1.8Kg\nUkuran layar LCD: 15,6 inci\nResolusi layar: 1920*1080\nModul sentuh TP\nJenis baterai: baterai polimer Li-ion 3.8v\nKapasitas: 5000mAh 7.6V\nWaktu kerja: 3-4 jam\n'
                                    '2. Konfigurasi perangkat keras sistem:\nTipe CPU: APOLLO LAKE J4105\nJenis GPU: Intel HD Graphics 500\nKapasitas memori: LPDDR4 6G\nKapasitas penyimpanan:8GB+256G\nKamera depan: 0,3M\nSpeaker internal: Speaker stereo internal 8R/1.0W*2\n'
                                    '3. Koneksi jaringan:\nModul WIFI: WIFI 802.11b/g/n&ac/a/b/g/n+BT\nModul Bluetooth: Bluetooth4.0\nEthernet: Enkripsi di luar jaringan\n4. Konfigurasi antarmuka:\nSlot kartu memori: Memori eksternal 1 kartu miniSD, maks 64GB\nAntarmuka USB: mendukung transmisi data, mendukung USB3.0*1+USB2.0*1\n'
                                    'Soket headphone: keluaran musik & Soket headphone standar 3,5 mm\nAntarmuka HDMI: Video Out Mikro HDMI Tipe D 1.4a\nPerangkat input keyboard: USB, dukungan kabel/nirkabel DT yang dapat diperluas\n5. Aksesori utama:\nAdaptor daya: standar DC 12V/2A\n'
                                    'Kabel data USB: host konfigurasi standar\nKonfigurasi perangkat lunak:\nSistem Operasi: Jendela Jendela 11/10'},
        {"no":"4",  "description": "Meja Laptop roda multifungsi dilengkapi roda sehingga yang bisa mudah dipindah-pindah. Meja juga dapat atur ketinggian meja sesuai keinginan ketika kerja di sofa/dikasur. Roda bisa di lock sehingga kerja lebih aman dan nyaman.\n\n"
                                    "Spec:\n- Warna : Maple, Hitam dan Putih\n- Ukuran : 60cm x 40cm x tinggi 70-90cm\n- Bahan :  Kayu Mdf, Dan Besi\n\nFitur :\n- Roda dapat dikunci/lock\n- Ketinggian dapat diatur\n- Design Fleksibel dan praktis\n- Mudah Dipindah-pindah"},
        {"no":"5",  "description": "Harga adalah harga perdus\n\n1 dus isi 40pcs\nexp masih lama\nHARGA  MULAI DARI 4 DUS/KARTON\nHARGA BISA BERUBAH SEWAKTU WAKTU"},
        {"no":"6",  "description": "Halo dan selamat datang di toko ; Produk yang kami sediakan berkualitas tinggi 100% asli dan asli, dan dikirim setelah pemeriksaan, jangan ragu untuk membeli, semua produk tersedia, selamat berbelanja ~\n\n"
                                    "100% Stok Siap Dikirim dari Jakarta,Indonesia\n【24 Hour Fast Ship, Average arrival time 1~3 days after ship!】\n【Ultra low price, Quality Assurance】\n【Double Check Before sending, Safe Packaging】\n\n"
                                    "Global Hot Sale, Highly recommended, Perfect gift for yourself or friends\nOnce you buy and use it, you will be satisfied!\nFitur:\n"
                                    "【4 Kabel Pengisi Daya Bawaan】 Bank daya portabel ini dilengkapi dengan 4 jalur data berbeda, yaitu Lightning, USB, Micro, type-c, yang dapat mengisi daya 4 perangkat berbeda secara bersamaan. Ini juga memberi Anda kabel USB universal sehingga Anda dapat membaginya dengan keluarga atau teman di mana saja.\n"
                                    "[Kapasitas Besar] Kapasitas 10000mAh dapat dengan mudah memenuhi kebutuhan daya harian Anda, dan bodinya yang ramping memungkinkan Anda membawanya dengan mudah tanpa khawatir. Jangan buang ruang.\n"
                                    "【Indikator Baterai LED】Power bank memiliki 4 indikator sehingga Anda dapat dengan jelas memahami tingkat dayanya. Mewakili 0-25%, 25-50%, 50-75%, 75-100%.\n"
                                    "【Mudah dibawa】terbuat dari baterai polimer lithium-ion ringan, beratnya hanya 205 gram dan panjang 62*58*27.5mm, mudah dibawa-bawa saat bepergian, untuk urusan bisnis atau bepergian tanpa menambah terlalu banyak beban.\n"
                                    "【Dua Senter Kuat】 Bank daya kami memiliki dua senter kuat, yang dapat mengirimkan sinyal marabahaya SOS dan tahan jatuh serta tahan debu. Itu masih dapat berfungsi bahkan di lingkungan yang ekstrim. Ini adalah pilihan tepat untuk aktivitas luar ruangan atau penggunaan sehari-hari.\n"
                                    "【Kompatibilitas Universal】 Menyediakan berbagi daya dan kabel dengan keluarga, teman, rekan kerja, dan bahkan orang asing! Bekerja dengan sebagian besar perangkat dan memiliki port USB untuk koneksi eksternal."},
        {"no":"7",  "description":"Deskripsi Produk\nModel : Vintage Chain rantai\nBahan : Miniso\nUkuran : 23x7x16 cm\nPenutup : Resleting\nProses bahan: Permukaan lembut\nEleman populer : Rantai\nTali : Kombinasi bahan dan rantai\nBahan : Kuat tidak mudah sobek\nWarna : Cerah tidak luntur"},
        {"no":"8",  "description":"• Bahan aluminium anti keropos\n• Lebih ringan dibanding kayu\n• Kokoh dengan rangka las besi dibagian roda\nGerobak Jualan Aluminium Pempek - Serbaguna cocok untuk berjualan untuk yang membutuhkan lobang kompor, dan lemari etalase penggunaan dapat disesuaikan\n"
                                    "Spesifikasi :\nDimensi - P120 x L50 x T180 cm\nBahan - Alumunium Hologot\nRoda - Las Rangka besi + Roda Nylon 3 inch\nPanel - Spanrel susun\nSiap melayani JABODETABEK, menerima model dan ukuran costum silahkan chat dan konsultasi ...\nDikirim menggunakan mobil toko kami untuk jaminan keamanan (Produk Kaca)"},
        {"no":"9",  "description":'Printer Smart Tank HP 500 Print Scan Copy Pengganti HP 315 all in one New\n(Barang selalu ready, silahkan diorder tanpa harus menanyakan stock terlebih dahulu)\nKami Menjual 3 tipe printer HP Smart Tank 500, diantaranya:\n\n1. Printer HP Smart Tank 500 with Original Ink (Tinta Original HP)\n\n2. Printer HP Smart Tank 500 with Premium Ink (Tinta premium compatible)\n\n3. Printer HP Smart Tank 500 with Premium Ink (Tinta premium Xantri)\n\n'
                                    'Spesifikasi:\n1. Printer HP Smart Tank 500 with Original Ink (Tinta Original HP)\n- 100% New Original Resmi HP Indonesia (mesin & Tinta)\n- Garansi Resmi Mesin dan Head Printer hingga 2 tahun\n- Hasil cetak Tajam kerena menggunakan tinta Original HP\n\n2. Printer HP Smart Tank 500 with Premium Ink (Tinta premium compatible)\n-100% New Original Resmi HP Indonesia (mesin)\n-Menggunakan tinta premium compatible kualitas terbaik\n'
                                    '-Garansi Resmi Mesin hingga 2 tahun\n- Hasil Cetak Tajam seperti menggunakan tinta original\n- Biaya cetak perlembar sangat murah\n\n3. Printer HP Smart Tank 500 with Premium Ink (Tinta premium Xantri)\n-100% New Original Resmi HP Indonesia (mesin)\nMenggunakan tinta kualitas premium super\n- Hasil cetak Tajam. langsung cepat kering\n- Tinta Xantri warna hitam pigment (tidak luntur, anti air) seperti original\n- Biaya cetak perlembar sangat murah dan aman untuk head\n'
                                    '- Printer Baru kondisi bersegel dan bergaransi Resmi dan hanya bisa di klaim ke service center resmi terdekat.\n- Kami tidak menerima penukaran / pengembalian dana yg diakibatkan karena printer error / rusak dr pabrik. Jika terdapat kendala / kerusakan printer silahkan datang langsung ke service center resmi.\n\nTerima kasih dan selamat berbelanja :-D'},
        {"no":"10", "description":'Printer Epson L3216 New, Printer Epson L3216 new, Printer Epson L3216 baru\nPrinter Epson L3216 adalah Printer pengganti tipe L3110\nEcoTank L3216 dirancang untuk meningkatkan penghematan biaya bisnis dan produktivitas cetak.\nHarapkan hasil cetak yang tinggi hingga 4.500 halaman untuk hitam-putih, dan 7.500 halaman untuk berwarna. Anda bahkan dapat mencetak foto tanpa bingkai hingga ukuran 4R. Tangki tinta terintegrasi dan nozel khusus memastikan pengisian ulang bebas tumpahan dan kesalahan.\n'
                                    'Apa saja yang di dapat :\nPrinter Baru Epson L3216 (Putih)\nNew Box\nKabel Power & Kabel USB\nCD Driver\nGaransi Resmi Epson\n\nSpesifikasi:\nPrinting Method\nEpson Micro Piezo™ print head\nNozzle Configuration\n180 Nozzles Black, 59 Nozzles per Color\nMinimum Droplet Size\n3 pl, With Variable-Sized Droplet Technology\nInk Technology\nDye Ink\nPrinting Resolution\n5,760 x 1,440 DPI\n\nCategory\nHome, Home Office\nAll-in-One Functions\nPrint, Scan, Copy\n\nPrint\nPrinting Speed ISO/IEC 24734\n'
                                    '10 pages/min Monochrome, 5 pages/min Colour, 69\nSeconds per 10 x 15 cm photo\n\nPrinting Speed\n15 pages/min Colour (plain paper 75 g/m²), 33 pages/ min Monochrome (plain paper 75 g/m²), 27 Seconds per 10 x 15 cm photo (Epson Premium Glossy Photo Paper)\n\nColours\nBlack, Cyan, Yellow, Magenta\n\nScan\nSingle-sided scan speed (A4 black)\n200 DPI;, 11 sec. with flatbed scan\nSingle-sided scan speed (A4 colour)\n200 DPI;, 32 sec. with flatbed scan\n\nOutput formats\n'
                                    'BMP, JPEG, PICT, TIFF, multi-TIFF, PDF, PNG\nScanner type\nContact image sensor (CIS)\nOptical Resolution\n600 DPI x 1,200 DPI (Horizontal x Vertical)\nPaper / Media Handling\nNumber of paper trays\nPaper Formats\nC6 (Envelope), B5 (17.6x25.7 cm), A6 (10.5x14.8 cm), A5 (14.8x21.0 cm), A4 (21.0x29.7 cm), Legal, User defined, 13 x 18 cm, 10 x 15 cm, Letter, No. 10 (Envelope), DL (Envelope), 16:9\nDuplex\nManual\nOutput Tray Capacity\n30 Sheets\nmultifunction\n100 Sheets Standard\n'
                                    'Compatible Paper Weight\n64 g/m²-300 g/m²\nMedia Handling\nBorderless print (up to 10 x 15cm)\nSupport Tinta Tipe:\nEpson 003 Black 2pcs'},
    ]
    return deskrip